# Generated by Django 2.2 on 2020-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='attachment',
            field=models.FileField(blank=True, upload_to='article_file/%Y%m%d/'),
        ),
    ]
