# Generated by Django 2.2 on 2021-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210422_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='isDischarged',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
