# Generated by Django 2.2 on 2021-06-11 03:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210422_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribe_patient', to='patient.Patient')),
            ],
        ),
    ]
