# Generated by Django 2.2 on 2021-06-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_patient_mr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribe_treatment', to='storage.Treatment'),
        ),
    ]
