# Generated by Django 2.2 on 2021-06-16 06:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_prescription_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='isDischarged',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
