# Generated by Django 2.2 on 2021-04-22 06:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('department', models.CharField(blank=True, choices=[('A', 'Anaesthesiology and Adult Intensive Care Department'), ('C', 'Child Surgical Department'), ('G', 'General and Vascular Surgical Department'), ('D', 'Dermatology'), ('O', 'Obstetric and Maternity Ward'), ('I', 'Internal Department'), ('L', 'Laryngology'), ('N', 'Neurology'), ('F', 'First-Aid Department')], max_length=1)),
                ('title', models.CharField(blank=True, choices=[('RN', 'RN'), ('CN', 'CNP'), ('PA', 'PA'), ('PH', 'Physician')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
